### ISSUE TITLE
PySCF version

### ISSUE THREAD

**Issue by vladislavivanistsev** [pyflosic/pyflosic#4]
Seems that PyFLOSIC requires a very specific version of PySCF: "class FLO: This code requires pyscf >= 1.5.2" and it does not work with the latest PySCF version of 1.7.6. How could that be fixed?

01_dft.py runs well, but python 02_flosic_os.py fails:
Ground state calculation: DONE.                                                                                                                                           
/home/vlad/anaconda3/lib/python3.8/site-packages/ase/atoms.py:967: VisibleDeprecationWarning: Use get_global_number_of_atoms() instead warnings.warn('Use get_global_number_of_atoms() instead',                                                                                                               /home/vlad/anaconda3/lib/python3.8/site-packages/ase/calculators/calculator.py:507: FutureWarning: The keyword "ignore_bad_restart_file" is deprecated and will be removed in a future version of ASE.  Passing more than one positional argument to Calculator is also deprecated and will stop functioning in the future.  Please pass arguments by keyword (key=value) except optionally the "restart" keyword.                                                                                                              warnings.warn(FutureWarning(                                                                                                                                            
class FLO: This code requires pyscf >= 1.5.2

**Comment by theonov13** [comment]
Dear Vladilsav Ivanistsev,

Sorry for the very late reply. 
As written in the introduction README.md,
we recommend the following package versions:

-    ase 3.17.0
-    h5py 2.10.0
-    numba 0.48.0
-    scipy 1.5.2
-    numpy 1.19.1
-    pyscf 1.7.1

Those can be easily set up using 
a virtual environment (see, init_venv.sh script).

ASE changed a lot of things 
and also PySCF has a lot of 
changes ongoing, therefore 
this version of PyFLOSIC may 
only work for the mentioned 
Python packages. 

We are working on a new release of PyFLOSIC 
which hopefully reaches a production-ready state 
in the near future. 

Best, 
Sebastian and Kai

**Comment by vladislavivanistsev** [comment]
Thank you for the clarification. Conda environment is indeed a suitable sandbox.
